# Generated by Django 4.1.7 on 2023-05-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='number_in_stock',
        ),
    ]
