# Generated by Django 4.2.1 on 2023-06-29 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Speciality', models.CharField(blank=True, max_length=60, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Categories', models.CharField(blank=True, max_length=30, null=True)),
                ('Summary', models.CharField(blank=True, max_length=2000, null=True)),
                ('Content', models.CharField(blank=True, max_length=10000, null=True)),
                ('Written_by', models.CharField(blank=True, default=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Categories', models.CharField(blank=True, max_length=30, null=True)),
                ('Summary', models.CharField(blank=True, max_length=2000, null=True)),
                ('Content', models.CharField(blank=True, max_length=10000, null=True)),
                ('Written_by', models.CharField(blank=True, default=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=30)),
                ('Dp', models.ImageField(blank=True, null=True, upload_to='')),
                ('Speciality', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
